# MLOps

<img data-ils="4" jsaction="rcuQ6b:trigger.M8vzZb;" class="rg_i Q4LuWd" jsname="Q4LuWd" width="360" height="119" alt="ML Ops: Machine Learning Operations" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIuAc5HoXRJxb0l7yKepV_v6n2bHurVxp7ww&amp;usqp=CAU">

$Step-1$: **Install required packages**

In [ ]:
!mlflow

/bin/bash: mlflow: command not found

In [ ]:
!pip install mlflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mlflow
  Downloading mlflow-2.2.2-py3-none-any.whl (17.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 64.4 MB/s eta 0:00:00
Collecting alembic<2
  Downloading alembic-1.10.3-py3-none-any.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.3/212.3 kB 24.1 MB/s eta 0:00:00
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.9/dist-packages (from mlflow) (3.7.1)
Requirement already satisfied: pyarrow<12,>=4.0.0 in /usr/local/lib/python3.9/dist-packages (from mlflow) (9.0.0)
Requirement already satisfied: pytz<2023 in /usr/local/lib/python3.9/dist-packages (from mlflow) (2022.7.1)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.9/dist-packages (from mlflow) (2.27.1)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.9/dist-packages (from mlflow) (0.4.3)
Requirement already satisfied: importlib-metadata!=4.7.0,<7,>=3.7.0 in /usr/local/lib/python3.9/dist-packages (from mlflow) (6.3.0)
Requirement already satisfied: Jinja2<4,>=2.11 in /usr/local/lib/python3.9/dist-packages (from mlflow) (3.1.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.9/dist-packages (from mlflow) (1.5.3)
Collecting gunicorn<21
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 10.6 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.9/dist-packages (from mlflow) (1.2.2)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.9/dist-packages (from mlflow) (1.10.1)
Collecting databricks-cli<1,>=0.8.7
  Downloading databricks-cli-0.17.6.tar.gz (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 9.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: markdown<4,>=3.3 in /usr/local/lib/python3.9/dist-packages (from mlflow) (3.4.3)
Collecting gitpython<4,>=2.1.0
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 24.1 MB/s eta 0:00:00
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.9/dist-packages (from mlflow) (8.1.3)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.9/dist-packages (from mlflow) (2.0.9)
Collecting shap<1,>=0.40
  Downloading shap-0.41.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (572 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.4/572.4 kB 53.0 MB/s eta 0:00:00
Collecting docker<7,>=4.0.0
  Downloading docker-6.0.1-py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.5/147.5 kB 21.1 MB/s eta 0:00:00
Collecting querystring-parser<2
  Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Requirement already satisfied: numpy<2 in /usr/local/lib/python3.9/dist-packages (from mlflow) (1.22.4)
Requirement already satisfied: entrypoints<1 in /usr/local/lib/python3.9/dist-packages (from mlflow) (0.4)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.9/dist-packages (from mlflow) (6.0)
Requirement already satisfied: packaging<24 in /usr/local/lib/python3.9/dist-packages (from mlflow) (23.0)
Requirement already satisfied: cloudpickle<3 in /usr/local/lib/python3.9/dist-packages (from mlflow) (2.2.1)
Requirement already satisfied: Flask<3 in /usr/local/lib/python3.9/dist-packages (from mlflow) (2.2.3)
Requirement already satisfied: protobuf<5,>=3.12.0 in /usr/local/lib/python3.9/dist-packages (from mlflow) (3.20.3)
Collecting Mako
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 12.6 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.9/dist-packages (from alembic<2->mlflow) (4.5.0)
Collecting pyjwt>=1.7.0
  Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
Requirement already satisfied: oauthlib>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from databricks-cli<1,>=0.8.7->mlflow) (3.2.2)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.9/dist-packages (from databricks-cli<1,>=0.8.7->mlflow) (0.8.10)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.9/dist-packages (from databricks-cli<1,>=0.8.7->mlflow) (1.16.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.9/dist-packages (from docker<7,>=4.0.0->mlflow) (1.26.15)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python3.9/dist-packages (from docker<7,>=4.0.0->mlflow) (1.5.1)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.9/dist-packages (from Flask<3->mlflow) (2.2.3)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.9/dist-packages (from Flask<3->mlflow) (2.1.2)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 8.3 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/dist-packages (from gunicorn<21->mlflow) (67.6.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata!=4.7.0,<7,>=3.7.0->mlflow) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from Jinja2<4,>=2.11->mlflow) (2.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (1.0.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (8.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (4.39.3)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (5.12.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.17.3->mlflow) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.17.3->mlflow) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.17.3->mlflow) (2.0.12)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn<2->mlflow) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn<2->mlflow) (3.1.0)
Collecting slicer==0.0.7
  Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
Requirement already satisfied: tqdm>4.25.0 in /usr/local/lib/python3.9/dist-packages (from shap<1,>=0.40->mlflow) (4.65.0)
Requirement already satisfied: numba in /usr/local/lib/python3.9/dist-packages (from shap<1,>=0.40->mlflow) (0.56.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.9/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (2.0.2)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /usr/local/lib/python3.9/dist-packages (from numba->shap<1,>=0.40->mlflow) (0.39.1)
Building wheels for collected packages: databricks-cli
  Building wheel for databricks-cli (setup.py) ... done
  Created wheel for databricks-cli: filename=databricks_cli-0.17.6-py3-none-any.whl size=143237 sha256=124bf7722955f99bc073d5867aa1fa0dc8e221bdea046ba21ce79f2719e2163d
  Stored in directory: /root/.cache/pip/wheels/06/d9/cb/1cdc0826334cb600957db0b5a8448db02a8995daeab2556745
Successfully built databricks-cli
Installing collected packages: smmap, slicer, querystring-parser, pyjwt, Mako, gunicorn, gitdb, docker, databricks-cli, alembic, shap, gitpython, mlflow
Successfully installed Mako-1.2.4 alembic-1.10.3 databricks-cli-0.17.6 docker-6.0.1 gitdb-4.0.10 gitpython-3.1.31 gunicorn-20.1.0 mlflow-2.2.2 pyjwt-2.6.0 querystring-parser-1.2.4 shap-0.41.0 slicer-0.0.7 smmap-5.0.0

In [ ]:
!mlflow

Usage: mlflow [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  artifacts    Upload, list, and download...
  db           Commands for managing an...
  deployments  Deploy MLflow models to custom...
  doctor       Prints out useful information for
               debugging issues with MLflow.
  experiments  Manage experiments.
  gc           Permanently delete runs in the
               `deleted` lifecycle stage.
  models       Deploy MLflow models locally.
  recipes      Run MLflow Recipes and inspect...
  run          Run an MLflow project from the...
  runs         Manage runs.
  sagemaker    Serve models on SageMaker.
  server       Run the MLflow tracking server.

In [ ]:
!mlflow --version

mlflow, version 2.2.2

$Step-2$ : **Import required packages**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import mlflow
import mlflow.sklearn

$Step-3$: **Read the data**

In [ ]:
data= pd.read_csv("/content/winequality_red.csv")
data.head()

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
# It is a supervised learning
# quality is outout columns has numerical data
# It is a regression problem

In [ ]:
data.shape

# This dataset has 1599 rows and 12 columns are there
# 11 columns are input columns (X)
# 1 column i.e quality is output/target (y)

(1599, 12)

In [ ]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
# Our interest is model development and deployment
# To develop model make sure we have all the columns have numerical data
# math works only on numbers
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [ ]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

$Step-4$: **Model development using Mlflow**

- We divide data into two parts train_data and test_data
- we divide train_data into X_train and y_train
- we divide test_data into X_test and y_test
- Model development happenes on train_data
- Model preictions happens on X_test data ,this will give y_predictions
- Finally I will compare y_predictions with y_test

In [ ]:
train,test= train_test_split(data,test_size=0.3,random_state=1234)
train.shape,test.shape

((1119, 12), (480, 12))

In [ ]:
train.head()

     fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
642            9.9             0.540         0.45  ...       0.62      9.4        5
678            8.3             0.780         0.10  ...       0.53     10.0        5
412            7.1             0.735         0.16  ...       0.64      9.3        5
73             8.3             0.675         0.26  ...       0.53      9.2        4
985            7.4             0.580         0.00  ...       0.58     11.3        6

[5 rows x 12 columns]

In [ ]:
# Now divide data into train_x and train_y
train_x=train.drop(['quality'],axis=1)
test_x= test.drop(['quality'],axis=1)

train_y=train[['quality']]
test_y=test[['quality']]

In [ ]:
train_x.shape,train_y.shape

((1119, 11), (1119, 1))

In [ ]:
test_x.shape,test_y.shape

((480, 11), (480, 1))

$Step-5$: **Start mlflow**

In [ ]:
# Mlflow is cloud platform
# I want to develop a model , deploy on mlflow
# Omkar create a model1 ------ mlflow
# Abhishek model1 ========= mlflow

# mlflow will create some workspace
# in the name of experiment

In [ ]:
mlflow.set_experiment("/mlflow/mlops_workspace")

2023/04/16 06:30:22 INFO mlflow.tracking.fluent: Experiment with name '/mlflow/mlops_workspace' does not exist. Creating a new experiment.

<Experiment: artifact_location='file:///content/mlruns/321444629570956532', creation_time=1681626622645, experiment_id='321444629570956532', last_update_time=1681626622645, lifecycle_stage='active', name='/mlflow/mlops_workspace', tags={}>

In [ ]:
print(mlflow.set_experiment("/mlflow/mlops_workspace").experiment_id)
print(mlflow.set_experiment("/mlflow/mlops_workspace").lifecycle_stage)
print(mlflow.set_experiment("/mlflow/mlops_workspace").name)

321444629570956532
active
/mlflow/mlops_workspace

In [ ]:
def train_model(alpha,l1_ratio):
    #=======Develop train test split============
    train,test= train_test_split(data,test_size=0.3,random_state=1234)
    train_x=train.drop(['quality'],axis=1)
    test_x= test.drop(['quality'],axis=1)
    train_y=train[['quality']]
    test_y=test[['quality']]

    #=========Intiate mlflow=============================
    with mlflow.start_run(experiment_id=321444629570956532,run_name='Regression',description='Performing a regression analysis'):
        #======== call ml model============
        lr=ElasticNet(alpha=alpha,l1_ratio=l1_ratio)
        lr.fit(train_x,train_y)

        #========Model prediction=============
        predicted_data=lr.predict(test_x)

        #========= Model evaluation==========

        rmse=np.sqrt(mean_squared_error(test_y,predicted_data))
        mae=mean_absolute_error(test_y,predicted_data)
        r2=r2_score(test_y,predicted_data)
        print("rmse:",rmse)
        print("mae:",mae)
        print("r2:",r2)

        #=======log the mertics,parameters and model on mlflow=======
        mlflow.log_param("alpha",alpha)
        mlflow.log_param("l1_ratio",l1_ratio)

        mlflow.log_metric("rmse",rmse)
        mlflow.log_metric("mae",mae)
        mlflow.log_metric("r2",r2)

        mlflow.sklearn.log_model(lr,"model",registered_model_name='ElasticNet')

In [ ]:
train_model(0.4,0.5)

rmse: 0.6940832047245566
mae: 0.5466837260017379
r2: 0.1552271885700255

Registered model 'ElasticNet' already exists. Creating a new version of this model...
2023/04/16 06:49:51 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: ElasticNet, version 2
Created version '2' of model 'ElasticNet'.

In [ ]:
# We need to show this on mlflow UI

$Step-6$: MlflowUi

In [ ]:
# To create Mlflow Ui from google colab notebook
# We need to create a tunnel

# tunnle name ======== ngrok

!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyngrok
  Downloading pyngrok-6.0.0.tar.gz (681 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 681.2/681.2 kB 34.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML in /usr/local/lib/python3.9/dist-packages (from pyngrok) (6.0)
Building wheels for collected packages: pyngrok
  Building wheel for pyngrok (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-6.0.0-py3-none-any.whl size=19879 sha256=ca5cc3649a57d795362daf7416355743fbad3cfc8a9e8f77bb725bbd9a9c448c
  Stored in directory: /root/.cache/pip/wheels/31/49/9c/44b13823eb256a3b4dff34b972f7a3c7d9910bfef269e59bd7
Successfully built pyngrok
Installing collected packages: pyngrok
Successfully installed pyngrok-6.0.0

In [ ]:
# create a tunnel
from pyngrok import ngrok
ngrok_tunnel=ngrok.connect(addr='5000',proto='http')
print("Tracking uri:",ngrok_tunnel.public_url)

WARNING:pyngrok.process.ngrok:t=2023-04-16T06:56:25+0000 lvl=warn msg="ngrok config file found at legacy location, move to XDG location" xdg_path=/root/.config/ngrok/ngrok.yml legacy_path=/root/.ngrok2/ngrok.yml

Tracking uri: https://c04e-35-199-0-111.ngrok.io

<div class="ant-col ant-col-sm-24 ant-col-lg-18 ant-col-xl-13"><h1 class="ant-typography" id="authtoken">Your Authtoken</h1><p class="cH1zG6wWq9mZVCFSudL9 _rz65p6nhEbCQ5T8181l">This is your personal Authtoken. Use this to authenticate the ngrok agent that you downloaded.</p><div class="ant-row" style="margin-left: -4px; margin-right: -4px; row-gap: 0px;"><div class="ant-col" style="padding-left: 4px; padding-right: 4px; flex: 1 1 auto;"><input class="ant-input" readonly="" type="text" value="2KVWElPAg1tzrBVnxmFFYaxfeyg_2cCYD9fH3HpMqU1u5TEsC"></div><div class="ant-col" style="padding-left: 4px; padding-right: 4px;"><button data-clipboard-text="2KVWElPAg1tzrBVnxmFFYaxfeyg_2cCYD9fH3HpMqU1u5TEsC" type="button" class="ant-btn ant-btn-primary"><span role="img" aria-label="copy" class="anticon anticon-copy"><svg viewBox="64 64 896 896" focusable="false" data-icon="copy" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M832 64H296c-4.4 0-8 3.6-8 8v56c0 4.4 3.6 8 8 8h496v688c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8V96c0-17.7-14.3-32-32-32zM704 192H192c-17.7 0-32 14.3-32 32v530.7c0 8.5 3.4 16.6 9.4 22.6l173.3 173.3c2.2 2.2 4.7 4 7.4 5.5v1.9h4.2c3.5 1.3 7.2 2 11 2H704c17.7 0 32-14.3 32-32V224c0-17.7-14.3-32-32-32zM382 896h-.2L232 746.2v-.2h150v150z"></path></svg></span><span>Copy</span></button></div></div></div>

In [ ]:
from pyngrok import ngrok
#======If any open tunnels are there close that==============
ngrok.kill()
auth_token="2KVWElPAg1tzrBVnxmFFYaxfeyg_2cCYD9fH3HpMqU1u5TEsC"

ngrok.set_auth_token(auth_token)

ngrok_tunnel=ngrok.connect(addr='5000',proto='http')
print("Tracking uri:",ngrok_tunnel.public_url)

WARNING:pyngrok.process.ngrok:t=2023-04-16T07:01:17+0000 lvl=warn msg="ngrok config file found at legacy location, move to XDG location" xdg_path=/root/.config/ngrok/ngrok.yml legacy_path=/root/.ngrok2/ngrok.yml

Tracking uri: https://9db3-35-199-0-111.ngrok-free.app

In [ ]:
!mlflow ui

[2023-04-16 07:01:47 +0000] [18508] [INFO] Starting gunicorn 20.1.0
[2023-04-16 07:01:47 +0000] [18508] [INFO] Listening at: http://127.0.0.1:5000 (18508)
[2023-04-16 07:01:47 +0000] [18508] [INFO] Using worker: sync
[2023-04-16 07:01:47 +0000] [18509] [INFO] Booting worker with pid: 18509
[2023-04-16 07:01:47 +0000] [18510] [INFO] Booting worker with pid: 18510
[2023-04-16 07:01:47 +0000] [18511] [INFO] Booting worker with pid: 18511
[2023-04-16 07:01:47 +0000] [18512] [INFO] Booting worker with pid: 18512
[2023-04-16 07:15:36 +0000] [18508] [INFO] Handling signal: int

Aborted!
[2023-04-16 07:15:36 +0000] [18509] [INFO] Worker exiting (pid: 18509)
[2023-04-16 07:15:36 +0000] [18511] [INFO] Worker exiting (pid: 18511)
[2023-04-16 07:15:36 +0000] [18510] [INFO] Worker exiting (pid: 18510)
[2023-04-16 07:15:36 +0000] [18512] [INFO] Worker exiting (pid: 18512)
[2023-04-16 07:15:37 +0000] [18508] [INFO] Shutting down: Master

In [ ]:
import mlflow
logged_model = 'runs:/72b9f25f30ed4202ad670e0baebcd416/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(test_x))

array([5.62819943, 5.58487094, 5.71948348, 5.78147552, 5.86244829,
       5.551803  , 5.80027927, 5.93912114, 5.66008195, 6.0809841 ,
       5.29031265, 5.4462568 , 5.79314019, 5.60654462, 5.67310506,
       5.4361623 , 5.14025254, 5.54448201, 5.6992845 , 5.15313546,
       5.06937031, 5.60378506, 5.45639998, 5.68895735, 5.78155307,
       5.80620707, 5.51415174, 5.25874731, 5.63431516, 5.68024811,
       5.23255392, 5.89280838, 5.29464238, 5.70638679, 5.51420344,
       5.40741314, 5.98105344, 5.54027456, 5.60952795, 5.9159041 ,
       5.35666724, 5.74096924, 5.71074839, 5.54881475, 5.49560063,
       5.36693777, 5.05203634, 5.87256071, 5.63886675, 5.48099831,
       5.33070158, 5.69470817, 5.92753102, 5.77870201, 5.67450823,
       5.61958661, 5.91157533, 5.58630789, 5.88130278, 5.56326086,
       5.74829323, 5.16332733, 5.29041605, 5.62537723, 5.32071049,
       5.79454637, 5.58196421, 5.93482123, 5.37708588, 5.79740536,
       5.8855808 , 5.79890987, 5.51268497, 5.9072724 , 5.25874731,
       5.47654425, 6.0691951 , 5.75549892, 5.14879273, 5.48087303,
       5.58354136, 5.47949475, 5.67034852, 5.79599426, 5.53720972,
       5.52435566, 5.81907904, 5.4289785 , 5.78727407, 5.67065681,
       5.95209652, 5.49105602, 5.74690798, 5.38846825, 5.79593558,
       5.88128089, 5.54884758, 5.79493454, 5.88852036, 6.0691951 ,
       5.61818946, 5.66728764, 5.07367323, 5.34522429, 5.59364585,
       5.43035281, 5.80318996, 5.63835261, 5.67743685, 5.69622267,
       5.71106763, 5.78159779, 5.9058096 , 5.67740402, 5.67603368,
       5.47786686, 5.71353776, 5.76842656, 5.94956866, 5.23545668,
       5.68506518, 5.76122785, 5.45936047, 5.96941161, 5.79892383,
       5.16901059, 5.62540704, 5.92176529, 5.82775847, 5.74255732,
       5.23254995, 5.08817802, 5.88705851, 5.24298653, 5.50400856,
       5.8900707 , 5.56335236, 5.62979941, 5.44635719, 5.52138724,
       5.67742987, 5.62398104, 5.4766586 , 5.28746159, 5.6168012 ,
       5.57633472, 5.63255405, 5.75012   , 5.92028061, 5.62965827,
       5.35101586, 5.69774415, 5.87279034, 5.97388851, 5.79447675,
       5.61720798, 5.70351384, 5.73536258, 6.01568362, 5.75842452,
       5.97673957, 5.66891553, 5.69181238, 5.51273271, 5.60224868,
       5.87978527, 5.61522405, 5.02321264, 5.73380732, 5.7265937 ,
       5.19210932, 5.5228123 , 5.30912734, 5.60088626, 6.10388396,
       5.64710261, 5.58631884, 5.53731613, 5.75547703, 4.94660845,
       5.53039083, 5.69688548, 5.85531619, 5.9954618 , 5.46510828,
       5.4232058 , 5.77718354, 5.71112028, 5.67894342, 5.75545118,
       5.78583808, 5.64127028, 5.46219156, 5.82511421, 5.57067636,
       5.09395468, 5.42031001, 6.10972723, 5.53149569, 5.4751073 ,
       5.63844903, 5.94193938, 5.63995163, 5.4029651 , 5.99262866,
       5.66878327, 5.72373962, 5.15900157, 5.22679914, 5.77569886,
       5.78877763, 5.53435469, 5.64276289, 5.50834526, 5.69781377,
       5.94051734, 5.50839997, 5.6701904 , 5.64265949, 5.72658672,
       5.597905  , 5.77277024, 5.24413146, 5.52438246, 5.57200595,
       5.28599879, 5.43035281, 5.66745273, 5.54298638, 5.67641857,
       5.75851301, 5.74243902, 5.58196421, 5.53150362, 5.60223774,
       5.62247446, 5.9217285 , 5.6298462 , 5.2326375 , 5.89438552,
       5.44781   , 5.47371809, 5.9535146 , 5.16037493, 5.60945833,
       5.34226586, 5.31055034, 5.6630066 , 5.91454169, 5.75559534,
       5.76711585, 5.75976901, 5.74248675, 5.53435469, 5.71659563,
       5.64857635, 5.49392897, 5.55176319, 5.74246487, 5.61970095,
       5.47823178, 5.41025231, 5.70064993, 5.78878461, 5.59788311,
       5.69345709, 5.61387861, 5.82195992, 5.62247843, 5.67450823,
       5.67309713, 5.60528165, 5.75264088, 5.81182863, 5.32802259,
       5.66313585, 6.03305041, 5.45488152, 5.41752857, 5.60374827,
       5.55494444, 5.48388712, 5.71645147, 5.44634926, 5.4882308 ,
       5.72223908, 5.61236506, 5.31781074, 5.54751102, 5.74107264,
       5.93904359, 5.77860559, 5.28165511, 5.69929544, 5.6400073 ,
       5.70345817, 5.63688283, 5.5560612 , 5.28599879, 5.49392897,
       5.54057192, 5.94630495, 5.69919506, 5.40149533, 5.89000108,
       5.87997018, 5.56190051, 5.53880177, 5.53014422, 5.23260467,
       5.36841247, 5.13293949, 5.8061265 , 5.47231095, 5.82496403,
       5.58056802, 5.08816707, 5.8525368 , 5.87112375, 5.20217797,
       5.79312433, 5.63549758, 5.60224868, 5.70638679, 5.46214683,
       5.03466654, 5.71112028, 5.55460331, 5.75545118, 5.46081027,
       5.88416177, 5.00732261, 5.91881479, 5.54871532, 5.34668313,
       5.62822528, 5.66153682, 5.51851334, 5.63258783, 5.75118109,
       6.09108954, 5.95789206, 5.73690499, 6.09828428, 5.4232058 ,
       5.30328898, 5.67603368, 5.48971057, 5.75432348, 5.67596406,
       5.59066252, 5.99112208, 5.23852057, 5.32360231, 5.83351326,
       5.25133879, 6.01281369, 5.63855544, 5.55605422, 5.62683607,
       5.72524921, 5.53581749, 5.48963397, 5.79465278, 5.99543595,
       5.87257165, 5.29604159, 5.60231529, 5.57205765, 5.92028061,
       5.47227416, 5.64706582, 5.66595805, 5.60367072, 5.70068371,
       5.87557575, 6.0604968 , 5.5502517 , 5.41883627, 4.63010848,
       5.5228123 , 5.6168261 , 5.43607777, 5.5906695 , 5.73673593,
       5.518399  , 5.30198731, 5.08242022, 5.36971388, 5.61233921,
       5.82496403, 5.75128148, 5.55603233, 5.53874214, 5.80027927,
       5.57768318, 5.07230986, 5.54737384, 5.48090982, 5.79758425,
       5.84225232, 5.24846885, 5.37988825, 5.57184387, 6.11575749,
       5.56325991, 5.88699492, 5.99832777, 5.78729992, 5.75405896,
       5.61530229, 5.57788601, 5.2325609 , 5.81199769, 5.77065954,
       5.49097847, 5.60824214, 5.39572262, 5.62532949, 5.49683966,
       5.70926767, 5.21524977, 5.86386637, 5.5589749 , 5.80610367,
       5.63553833, 5.03763591, 5.9405581 , 6.12282393, 5.66737011,
       5.62821037, 5.90724259, 5.54011645, 5.80179472, 5.32645433,
       5.65152685, 5.33807331, 5.84945103, 5.6818262 , 5.75265578,
       5.58629299, 4.69365181, 5.52140913, 5.54751102, 5.87256071,
       5.54736686, 5.43330029, 5.20357416, 5.02609749, 5.63255405,
       5.79465278, 5.55743154, 5.70788638, 5.78165251, 5.53000007,
       5.77143764, 5.84109084, 5.28328697, 5.48960019, 5.72079515,
       5.77870201, 5.56066872, 5.31055034, 5.65431226, 5.7062983 ,
       5.62412424, 6.07063903, 5.48087303, 5.52438246, 5.27446132,
       5.48526841, 5.62685097, 5.48247206, 5.15457542, 5.9636091 ,
       5.6976149 , 5.90295854, 5.92320716, 5.80893681, 5.7713482 ])